In [1]:
import numpy as np

In [3]:
# Ein 3D-Array, das ein 2x2 Bild mit 3 Farbkanälen (RGB) darstellt
array_3d = np.array([[[255, 128, 0], [0, 255, 0]],
                     [[0, 0, 255], [255, 255, 255]]])

# Division durch 255
normalized_array_3d = array_3d / 255.0
print(normalized_array_3d)


[[[1.         0.50196078 0.        ]
  [0.         1.         0.        ]]

 [[0.         0.         1.        ]
  [1.         1.         1.        ]]]


In [4]:
import numpy as np

# Ein 4-dimensionales Array erstellen (z.B. ein Batch von Bildern in einem RGB-Format)
array_4d = np.random.randint(0, 256, (2, 2, 2, 3))

print("Original Array:")
print(array_4d)

# Division durch 255
normalized_array_4d = array_4d / 255.0

print("\nNormalisiertes Array:")
print(normalized_array_4d)


Original Array:
[[[[211  39 138]
   [ 31 178  85]]

  [[216 102 198]
   [125 118 123]]]


 [[[234  78  33]
   [  5 214 254]]

  [[ 67  11  39]
   [ 18 133  83]]]]

Normalisiertes Array:
[[[[0.82745098 0.15294118 0.54117647]
   [0.12156863 0.69803922 0.33333333]]

  [[0.84705882 0.4        0.77647059]
   [0.49019608 0.4627451  0.48235294]]]


 [[[0.91764706 0.30588235 0.12941176]
   [0.01960784 0.83921569 0.99607843]]

  [[0.2627451  0.04313725 0.15294118]
   [0.07058824 0.52156863 0.3254902 ]]]]


In [ ]:
# relu function
def relu(x):
    return np.maximum(0, x)

In [76]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.initializers import Constant
from tensorflow.keras.regularizers import l2

# Erstellen einer Dense-Schicht mit 1 Neuron und ReLU-Aktivierung
dense_layer = tf.keras.layers.Dense(1, activation='relu', input_shape=(3,),bias_initializer=Constant(0.1))
# dense_layer = tf.keras.layers.Dense(1, activation='relu', input_shape=(3,),bias_regularizer=l2(1))

# Erstellen eines Modells, das diese Schicht enthält
model = tf.keras.models.Sequential([dense_layer])

# Initialisieren des Modells mit zufälligen Gewichten
model.compile(optimizer='sgd', loss='mean_squared_error')

# Eingabedaten: ein 1x3 Array
input_data = np.array([[1.0, 2.0, 3.0]])

# Voraussage durchführen
output = model.predict(input_data)

# Ausgabe der Resultate
print("Eingabedaten:", input_data)
print("Ausgabe der Dense-Schicht:", output)
print("Gewichte (Weights):", dense_layer.get_weights()[0])
print("Bias (Biases):", dense_layer.get_weights()[1])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
Eingabedaten: [[1. 2. 3.]]
Ausgabe der Dense-Schicht: [[0.2665392]]
Gewichte (Weights): [[-0.16676378]
 [ 0.23313022]
 [-0.04431915]]
Bias (Biases): [0.1]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
Eingabedaten: [[1. 2. 3.]]
Ausgabe der Dense-Schicht: [[0.2665392]]
Gewichte (Weights): [[-0.16676378]
 [ 0.23313022]
 [-0.04431915]]
Bias (Biases): [0.1]


In [9]:
# sdg funktion
def sgd(weights, gradients, learning_rate):
    updated_weights = weights - learning_rate * gradients
    return updated_weights

result = sgd(np.array([1, 2, 3]), np.array([0.1, 0.2, 0.3]), 0.01)
print(result)

[0.999 1.998 2.997]


In [79]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

def dense_layer(inputs, weights, bias):
    """
    Führt eine Berechnung in einer Dense-Schicht durch.
    
    Args:
    inputs (numpy.array): Eingabewerte zur Schicht.
    weights (numpy.array): Gewichtsmatrix der Schicht.
    bias (numpy.array): Bias-Vektor der Schicht.
    
    Returns:
    numpy.array: Die aktivierten Ausgaben der Schicht.
    """
    z = np.dot(weights, inputs) + bias
    a = relu(z)
    return a

# Beispiel für Eingabewerte
inputs = np.array([1.5, 2.0, 3.0])

# Beispielgewichte und Bias für eine Schicht mit 3 Eingängen und 2 Ausgängen
weights = np.array([
    [0.2, -0.3, 0.5],
    [-0.6, 0.7, 0.1]
])
bias = np.array([0.1, -0.1])

# Ausführen der Dense-Schicht
output = dense_layer(inputs, weights, bias)
print("Output der Dense-Schicht:", output)


Output der Dense-Schicht: [1.3 0.7]


In [88]:
def manuelle_dot(matrix, vektor):
    """
    Multipliziert eine Matrix mit einem Vektor und gibt das Ergebnis zurück.

    Args:
    matrix (list of list of float): Die Matrix der Gewichte.
    vektor (list of float): Der Vektor der Eingänge.

    Returns:
    list of float: Das Ergebnis der Matrix-Vektor-Multiplikation.
    """
    ergebnis = []
    # Gehe durch jede Zeile der Matrix
    for zeile in matrix:
        summe = 0
        # Multipliziere jedes Element der Zeile mit dem entsprechenden Element des Vektors
        for i in range(len(vektor)):
            summe += zeile[i] * vektor[i]
        # Füge die summierte Zahl zum Ergebnisvektor hinzu
        ergebnis.append(summe)
    return ergebnis

# Beispiel für Eingabewerte
# inputs = [1.5, 2.0, 3.0]
# randomized inpunts
inputs = np.random.randint(0, 10, 3)
print("inputs:", inputs)

# Beispielgewichte und Bias für eine Schicht mit 3 Eingängen und 2 Ausgängen
weights = [
    [0.2, -0.3, 0.5],
    [-0.6, 0.7, 0.1]
]
bias = [0.1, -0.1]

# Ausführen der manuellen Matrix-Vektor-Multiplikation
z = manuelle_dot(weights, inputs)
print("Ergebnis von DOT:", z)

# Hinzufügen des Bias zu jedem Element des Ergebnisvektors
z = [z[i] + bias[i] for i in range(len(bias))]
print("Ergebnis inkl. Bias:", z, " | Bias: ",bias)


# Anwenden der ReLU Funktion
output = [max(0, x) for x in z]

print("Output der Dense-Schicht (Relu):", output)


inputs: [3 9 5]
Ergebnis von DOT: [0.40000000000000036, 5.0]
Ergebnis inkl. Bias: [0.5000000000000003, 4.9]  | Bias:  [0.1, -0.1]
Output der Dense-Schicht (Relu): [0.5000000000000003, 4.9]


In [103]:
import numpy as np

def softmax(logits):
    # Verhindert Überlauf
    exp_shifted = np.exp(logits - np.max(logits))
    # exp_shifted = np.exp(logits )
    print("exp_shifted:", exp_shifted)
    # Berechnung der Softmax-Wahrscheinlichkeiten
    probabilities = exp_shifted / np.sum(exp_shifted)
    return probabilities

# Beispiel für Logits
logits = np.array([2.0, 1.0, 0.1])

# Anwendung der Softmax-Funktion
probabilities = softmax(logits)
print("Softmax Wahrscheinlichkeiten:", probabilities)
print("Summe der Wahrscheinlichkeiten:", np.sum(probabilities))


exp_shifted: [1.         0.36787944 0.14956862]
Softmax Wahrscheinlichkeiten: [0.65900114 0.24243297 0.09856589]
Summe der Wahrscheinlichkeiten: 1.0


In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Angenommen, data ist dein vorbereiteter Datensatz, der in passender Form vorliegt
# Beispiel: data = np.random.rand(1000, 10, 6) # 1000 Samples, 10 Zeitpunkte, 6 Features (5 numerische Werte + 1 Zeitstempel)

# Modelldefinition
model = Sequential([
    LSTM(50, return_sequences=True, input_shape=(10, 6)),  # 10 Zeitpunkte, 6 Features
    LSTM(50),
    Dense(1)  # oder Dense(n) für n Klassen bei Klassifizierungsproblemen
])

# Modell kompilieren
model.compile(optimizer='adam', loss='mse')  # 'mse' für Regression, 'categorical_crossentropy' für Klassifikation

# Modell trainieren
history = model.fit(data, labels, epochs=20, validation_split=0.2)


c:\Users\a.denisov\Documents\Dev\sandbox\nn_stocks\.env\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


NameError: name 'labels' is not defined

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Angenommen, data ist dein vorbereiteter Datensatz, der in passender Form vorliegt
data = np.random.rand(1000, 10, 6) # 1000 Samples, 10 Zeitpunkte, 6 Features (5 numerische Werte + 1 Zeitstempel)

In [3]:

# get data from yfinance
import yfinance as yf

# get minute data for the last 5 days
ticker = 'AAPL'
period = '1y'
interval = '1m'
df = yf.download(ticker, period=period, interval=interval)


[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['AAPL']: YFChartError('%ticker%: 1m data not available for startTime=1687953271 and endTime=1719489271. Only 7 days worth of 1m granularity data are allowed to be fetched per request.')


1 Failed download:
['AAPL']: YFChartError('%ticker%: 1m data not available for startTime=1687953271 and endTime=1719489271. Only 7 days worth of 1m granularity data are allowed to be fetched per request.')
